// <auto-generated />
using System;
using EmployeeProcessor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeProcessor.Data.Migrations
{
    [DbContext(typeof(EmployeeProcessorDbContext))]
    [Migration("20220506212913_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeProcessor.Data.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeePayId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeResponsibilityId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeePayId");

                    b.HasIndex("EmployeeResponsibilityId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeProcessor.Data.Models.EmployeePay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AnnualSalaryAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PayPerHourAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PayType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeePays");
                });

            modelBuilder.Entity("EmployeeProcessor.Data.Models.EmployeeResponsibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EmployeeRank")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxExpenseAccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PayType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeResponsibilities");
                });

            modelBuilder.Entity("EmployeeProcessor.Data.Models.Employee", b =>
                {
                    b.HasOne("EmployeeProcessor.Data.Models.EmployeePay", "EmployeePay")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeePayId");

                    b.HasOne("EmployeeProcessor.Data.Models.EmployeeResponsibility", "EmployeeResponsibility")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeResponsibilityId");

                    b.Navigation("EmployeePay");

                    b.Navigation("EmployeeResponsibility");
                });

            modelBuilder.Entity("EmployeeProcessor.Data.Models.EmployeePay", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmployeeProcessor.Data.Models.EmployeeResponsibility", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
